apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: my-frontend-image:v1
          ports:
            - containerPort: 3000
