version: "3.7"


services:
  item-app:
    image: "taqwimcore/item-app:v1"
    ports:
      - 80:8080
    networks:
      - item-network
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    ports:
      - 27017:27017
    networks:
      - item-network
    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db:

networks:
  item-network:
    driver: bridge