apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: config
          mountPath: /config
        - name: mongo-credentials
          mountPath: /etc/mongo-credentials
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-pv
      - name: config
        configMap:
          name: mongo-configmap
      - name: mongo-credentials
        secret:
          secretName: mongo-secret
