# deklarasi apiVersion yang digunakan adalah apps/v1. Abstraksi tingkat tinggi seperti StatefulSet memiliki API group-nya sendiri sehingga bukan bagian dari API inti.
apiVersion: apps/v1
# deklarasi kind yang mengindikasikan resource yang didefinisikan, yaitu StatefulSet
kind: StatefulSet
metadata:
  name: mongo-state
  labels:
    app: mongo
    tier: db
spec:
  selector:
    matchLabels:
      app: mongo
      tier: db
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
        - name: mongo-configmap
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-configmap
        configMap:
          name: mongo-configmap
      - name: mongo-secret
        secret:
          secretName: mongo-secret